FROM alpine
RUN echo "First layer" > /index.html
RUN echo "Second layer" > /index1.html
RUN rm index1.html
RUN apk update && apk upgrade && apk add curl
EXPOSE 8080
RUN echo "Third layer" > /index2.html
CMD ["cat", "/index.html"]