FROM python:3.9-slim
WORKDIR /app
RUN pip install --upgrade pip && pip install pipenv
# Copy Pipfile and Pipfile.lock to the container
# Install dependencies using pipenv (pipenv install)
# Copy all files to the container
# Remeber to expose port
ENV HOST=0.0.0.0
CMD ["pipenv", "run", "python", "main.py"]